<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Workflow_steps;

class Workflow_step_seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Workflow_steps::insert([
            //1
            ['workflow_id'=>1, 'sequence_no'=>1, 'office_reference'=>'Applicant', 'role_id'=>1],
            ['workflow_id'=>1, 'sequence_no'=>2, 'office_reference'=>'Institute', 'role_id'=>2],
            ['workflow_id'=>1, 'sequence_no'=>3, 'office_reference'=>'Institute', 'role_id'=>3],
            ['workflow_id'=>1, 'sequence_no'=>4, 'office_reference'=>'Institute', 'role_id'=>4],
            ['workflow_id'=>1, 'sequence_no'=>5, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>2],
            ['workflow_id'=>1, 'sequence_no'=>6, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>3],
            ['workflow_id'=>1, 'sequence_no'=>7, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>4],
            ['workflow_id'=>1, 'sequence_no'=>8, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>5],
            ['workflow_id'=>1, 'sequence_no'=>9, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>6],
            ['workflow_id'=>1, 'sequence_no'=>10, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>7],

            //2
            ['workflow_id'=>2, 'sequence_no'=>1, 'office_reference'=>'Applicant', 'role_id'=>1],
            ['workflow_id'=>2, 'sequence_no'=>2, 'office_reference'=>'Institute', 'role_id'=>2],
            ['workflow_id'=>2, 'sequence_no'=>3, 'office_reference'=>'Institute', 'role_id'=>3],
            ['workflow_id'=>2, 'sequence_no'=>4, 'office_reference'=>'Institute', 'role_id'=>4],
            ['workflow_id'=>2, 'sequence_no'=>5, 'office_reference'=>'පාලන අංශය', 'role_id'=>2],
            ['workflow_id'=>2, 'sequence_no'=>6, 'office_reference'=>'පාලන අංශය', 'role_id'=>3],
            ['workflow_id'=>2, 'sequence_no'=>7, 'office_reference'=>'පාලන අංශය', 'role_id'=>4],
            ['workflow_id'=>2, 'sequence_no'=>8, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>2],
            ['workflow_id'=>2, 'sequence_no'=>9, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>3],
            ['workflow_id'=>2, 'sequence_no'=>10, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>4],
            ['workflow_id'=>2, 'sequence_no'=>11, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>5],
            ['workflow_id'=>2, 'sequence_no'=>12, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>6],
            ['workflow_id'=>2, 'sequence_no'=>13, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>7],

            //3
            ['workflow_id'=>3, 'sequence_no'=>1, 'office_reference'=>'Applicant', 'role_id'=>1],
            ['workflow_id'=>3, 'sequence_no'=>2, 'office_reference'=>'Institute', 'role_id'=>2],
            ['workflow_id'=>3, 'sequence_no'=>3, 'office_reference'=>'Institute', 'role_id'=>3],
            ['workflow_id'=>3, 'sequence_no'=>4, 'office_reference'=>'Institute', 'role_id'=>4],
            ['workflow_id'=>3, 'sequence_no'=>5, 'office_reference'=>'දකුණු පළාත් ප්‍රධාන අමාත්‍යංශය', 'role_id'=>2],
            ['workflow_id'=>3, 'sequence_no'=>6, 'office_reference'=>'දකුණු පළාත් ප්‍රධාන අමාත්‍යංශය', 'role_id'=>3],
            ['workflow_id'=>3, 'sequence_no'=>7, 'office_reference'=>'දකුණු පළාත් ප්‍රධාන අමාත්‍යංශය', 'role_id'=>4],
            ['workflow_id'=>3, 'sequence_no'=>8, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>2],
            ['workflow_id'=>3, 'sequence_no'=>9, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>3],
            ['workflow_id'=>3, 'sequence_no'=>10, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>4],
            ['workflow_id'=>3, 'sequence_no'=>11, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>5],
            ['workflow_id'=>3, 'sequence_no'=>12, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>6],
            ['workflow_id'=>3, 'sequence_no'=>13, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>7],

            //4
            ['workflow_id'=>4, 'sequence_no'=>1, 'office_reference'=>'Applicant', 'role_id'=>1],
            ['workflow_id'=>4, 'sequence_no'=>2, 'office_reference'=>'Institute', 'role_id'=>2],
            ['workflow_id'=>4, 'sequence_no'=>3, 'office_reference'=>'Institute', 'role_id'=>3],
            ['workflow_id'=>4, 'sequence_no'=>4, 'office_reference'=>'Institute', 'role_id'=>4],
            ['workflow_id'=>4, 'sequence_no'=>5, 'office_reference'=>'දකුණු පළාත් අධ්‍යාපන අමාත්‍යංශය', 'role_id'=>2],
            ['workflow_id'=>4, 'sequence_no'=>6, 'office_reference'=>'දකුණු පළාත් අධ්‍යාපන අමාත්‍යංශය', 'role_id'=>3],
            ['workflow_id'=>4, 'sequence_no'=>7, 'office_reference'=>'දකුණු පළාත් අධ්‍යාපන අමාත්‍යංශය', 'role_id'=>4],
            ['workflow_id'=>4, 'sequence_no'=>8, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>2],
            ['workflow_id'=>4, 'sequence_no'=>9, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>3],
            ['workflow_id'=>4, 'sequence_no'=>10, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>4],
            ['workflow_id'=>4, 'sequence_no'=>11, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>5],
            ['workflow_id'=>4, 'sequence_no'=>12, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>6],
            ['workflow_id'=>4, 'sequence_no'=>13, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>7],

            //5
            ['workflow_id'=>5, 'sequence_no'=>1, 'office_reference'=>'Applicant', 'role_id'=>1],
            ['workflow_id'=>5, 'sequence_no'=>2, 'office_reference'=>'Institute', 'role_id'=>2],
            ['workflow_id'=>5, 'sequence_no'=>3, 'office_reference'=>'Institute', 'role_id'=>3],
            ['workflow_id'=>5, 'sequence_no'=>4, 'office_reference'=>'Institute', 'role_id'=>4],
            ['workflow_id'=>5, 'sequence_no'=>5, 'office_reference'=>'දකුණු පළාත් කෘෂිකර්ම අමාත්‍යංශය', 'role_id'=>2],
            ['workflow_id'=>5, 'sequence_no'=>6, 'office_reference'=>'දකුණු පළාත් කෘෂිකර්ම අමාත්‍යංශය', 'role_id'=>3],
            ['workflow_id'=>5, 'sequence_no'=>7, 'office_reference'=>'දකුණු පළාත් කෘෂිකර්ම අමාත්‍යංශය', 'role_id'=>4],
            ['workflow_id'=>5, 'sequence_no'=>8, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>2],
            ['workflow_id'=>5, 'sequence_no'=>9, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>3],
            ['workflow_id'=>5, 'sequence_no'=>10, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>4],
            ['workflow_id'=>5, 'sequence_no'=>11, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>5],
            ['workflow_id'=>5, 'sequence_no'=>12, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>6],
            ['workflow_id'=>5, 'sequence_no'=>13, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>7],

            //6
            ['workflow_id'=>6, 'sequence_no'=>1, 'office_reference'=>'Applicant', 'role_id'=>1],
            ['workflow_id'=>6, 'sequence_no'=>2, 'office_reference'=>'Institute', 'role_id'=>2],
            ['workflow_id'=>6, 'sequence_no'=>3, 'office_reference'=>'Institute', 'role_id'=>3],
            ['workflow_id'=>6, 'sequence_no'=>4, 'office_reference'=>'Institute', 'role_id'=>4],
            ['workflow_id'=>6, 'sequence_no'=>5, 'office_reference'=>'දකුණු පළාත් ධීවර අමාත්‍යංශය', 'role_id'=>2],
            ['workflow_id'=>6, 'sequence_no'=>6, 'office_reference'=>'දකුණු පළාත් ධීවර අමාත්‍යංශය', 'role_id'=>3],
            ['workflow_id'=>6, 'sequence_no'=>7, 'office_reference'=>'දකුණු පළාත් ධීවර අමාත්‍යංශය', 'role_id'=>4],
            ['workflow_id'=>6, 'sequence_no'=>8, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>2],
            ['workflow_id'=>6, 'sequence_no'=>9, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>3],
            ['workflow_id'=>6, 'sequence_no'=>10, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>4],
            ['workflow_id'=>6, 'sequence_no'=>11, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>5],
            ['workflow_id'=>6, 'sequence_no'=>12, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>6],
            ['workflow_id'=>6, 'sequence_no'=>13, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>7],

            //7
            ['workflow_id'=>7, 'sequence_no'=>1, 'office_reference'=>'Applicant', 'role_id'=>1],
            ['workflow_id'=>7, 'sequence_no'=>2, 'office_reference'=>'Institute', 'role_id'=>2],
            ['workflow_id'=>7, 'sequence_no'=>3, 'office_reference'=>'Institute', 'role_id'=>3],
            ['workflow_id'=>7, 'sequence_no'=>4, 'office_reference'=>'Institute', 'role_id'=>4],
            ['workflow_id'=>7, 'sequence_no'=>5, 'office_reference'=>'දකුණු පළාත් ක්‍රීඩා අමාත්‍යංශය', 'role_id'=>2],
            ['workflow_id'=>7, 'sequence_no'=>6, 'office_reference'=>'දකුණු පළාත් ක්‍රීඩා අමාත්‍යංශය', 'role_id'=>3],
            ['workflow_id'=>7, 'sequence_no'=>7, 'office_reference'=>'දකුණු පළාත් ක්‍රීඩා අමාත්‍යංශය', 'role_id'=>4],
            ['workflow_id'=>7, 'sequence_no'=>8, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>2],
            ['workflow_id'=>7, 'sequence_no'=>9, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>3],
            ['workflow_id'=>7, 'sequence_no'=>10, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>4],
            ['workflow_id'=>7, 'sequence_no'=>11, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>5],
            ['workflow_id'=>7, 'sequence_no'=>12, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>6],
            ['workflow_id'=>7, 'sequence_no'=>13, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>7],

            //8
            ['workflow_id'=>8, 'sequence_no'=>1, 'office_reference'=>'Applicant', 'role_id'=>1],
            ['workflow_id'=>8, 'sequence_no'=>2, 'office_reference'=>'Institute', 'role_id'=>2],
            ['workflow_id'=>8, 'sequence_no'=>3, 'office_reference'=>'Institute', 'role_id'=>3],
            ['workflow_id'=>8, 'sequence_no'=>4, 'office_reference'=>'Institute', 'role_id'=>4],
            ['workflow_id'=>8, 'sequence_no'=>5, 'office_reference'=>'දකුණු පළාත් පළාත් පාලන දෙපාර්තමේන්තුව', 'role_id'=>2],
            ['workflow_id'=>8, 'sequence_no'=>6, 'office_reference'=>'දකුණු පළාත් පළාත් පාලන දෙපාර්තමේන්තුව', 'role_id'=>3],
            ['workflow_id'=>8, 'sequence_no'=>7, 'office_reference'=>'දකුණු පළාත් පළාත් පාලන දෙපාර්තමේන්තුව', 'role_id'=>4],
            ['workflow_id'=>8, 'sequence_no'=>8, 'office_reference'=>'දකුණු පළාත් ප්‍රධාන අමාත්‍යංශය', 'role_id'=>2],
            ['workflow_id'=>8, 'sequence_no'=>9, 'office_reference'=>'දකුණු පළාත් ප්‍රධාන අමාත්‍යංශය', 'role_id'=>3],
            ['workflow_id'=>8, 'sequence_no'=>10, 'office_reference'=>'දකුණු පළාත් ප්‍රධාන අමාත්‍යංශය', 'role_id'=>4],
            ['workflow_id'=>8, 'sequence_no'=>11, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>2],
            ['workflow_id'=>8, 'sequence_no'=>12, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>3],
            ['workflow_id'=>8, 'sequence_no'=>13, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>4],
            ['workflow_id'=>8, 'sequence_no'=>14, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>5],
            ['workflow_id'=>8, 'sequence_no'=>15, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>6],
            ['workflow_id'=>8, 'sequence_no'=>16, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>7],

            //9
            ['workflow_id'=>9, 'sequence_no'=>1, 'office_reference'=>'Applicant', 'role_id'=>1],
            ['workflow_id'=>9, 'sequence_no'=>2, 'office_reference'=>'Institute', 'role_id'=>2],
            ['workflow_id'=>9, 'sequence_no'=>3, 'office_reference'=>'Institute', 'role_id'=>3],
            ['workflow_id'=>9, 'sequence_no'=>4, 'office_reference'=>'Institute', 'role_id'=>4],
            ['workflow_id'=>9, 'sequence_no'=>5, 'office_reference'=>'දකුණු පළාත් පළාත් අධ්‍යාපන දෙපාර්තමේන්තුව', 'role_id'=>2],
            ['workflow_id'=>9, 'sequence_no'=>6, 'office_reference'=>'දකුණු පළාත් පළාත් අධ්‍යාපන දෙපාර්තමේන්තුව', 'role_id'=>3],
            ['workflow_id'=>9, 'sequence_no'=>7, 'office_reference'=>'දකුණු පළාත් පළාත් අධ්‍යාපන දෙපාර්තමේන්තුව', 'role_id'=>4],
            ['workflow_id'=>9, 'sequence_no'=>8, 'office_reference'=>'දකුණු පළාත් අධ්‍යාපන අමාත්‍යංශය', 'role_id'=>2],
            ['workflow_id'=>9, 'sequence_no'=>9, 'office_reference'=>'දකුණු පළාත් අධ්‍යාපන අමාත්‍යංශය', 'role_id'=>3],
            ['workflow_id'=>9, 'sequence_no'=>10, 'office_reference'=>'දකුණු පළාත් අධ්‍යාපන අමාත්‍යංශය', 'role_id'=>4],
            ['workflow_id'=>9, 'sequence_no'=>11, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>2],
            ['workflow_id'=>9, 'sequence_no'=>12, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>3],
            ['workflow_id'=>9, 'sequence_no'=>13, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>4],
            ['workflow_id'=>9, 'sequence_no'=>14, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>5],
            ['workflow_id'=>9, 'sequence_no'=>15, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>6],
            ['workflow_id'=>9, 'sequence_no'=>16, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>7],

            //10
            ['workflow_id'=>10, 'sequence_no'=>1, 'office_reference'=>'Applicant', 'role_id'=>1],
            ['workflow_id'=>10, 'sequence_no'=>2, 'office_reference'=>'Institute', 'role_id'=>2],
            ['workflow_id'=>10, 'sequence_no'=>3, 'office_reference'=>'Institute', 'role_id'=>3],
            ['workflow_id'=>10, 'sequence_no'=>4, 'office_reference'=>'Institute', 'role_id'=>4],
            ['workflow_id'=>10, 'sequence_no'=>5, 'office_reference'=>'දකුණු පළාත් සහකාර පළාත් පාලන දෙපාර්තමේන්තුව - ගාල්ල', 'role_id'=>2],
            ['workflow_id'=>10, 'sequence_no'=>6, 'office_reference'=>'දකුණු පළාත් සහකාර පළාත් පාලන දෙපාර්තමේන්තුව - ගාල්ල', 'role_id'=>3],
            ['workflow_id'=>10, 'sequence_no'=>7, 'office_reference'=>'දකුණු පළාත් සහකාර පළාත් පාලන දෙපාර්තමේන්තුව - ගාල්ල', 'role_id'=>4],
            ['workflow_id'=>10, 'sequence_no'=>8, 'office_reference'=>'දකුණු පළාත් පළාත් පාලන දෙපාර්තමේන්තුව', 'role_id'=>2],
            ['workflow_id'=>10, 'sequence_no'=>9, 'office_reference'=>'දකුණු පළාත් පළාත් පාලන දෙපාර්තමේන්තුව', 'role_id'=>3],
            ['workflow_id'=>10, 'sequence_no'=>10, 'office_reference'=>'දකුණු පළාත් පළාත් පාලන දෙපාර්තමේන්තුව', 'role_id'=>4],
            ['workflow_id'=>10, 'sequence_no'=>11, 'office_reference'=>'දකුණු පළාත් ප්‍රධාන අමාත්‍යංශය', 'role_id'=>2],
            ['workflow_id'=>10, 'sequence_no'=>12, 'office_reference'=>'දකුණු පළාත් ප්‍රධාන අමාත්‍යංශය', 'role_id'=>3],
            ['workflow_id'=>10, 'sequence_no'=>13, 'office_reference'=>'දකුණු පළාත් ප්‍රධාන අමාත්‍යංශය', 'role_id'=>4],
            ['workflow_id'=>10, 'sequence_no'=>14, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>2],
            ['workflow_id'=>10, 'sequence_no'=>15, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>3],
            ['workflow_id'=>10, 'sequence_no'=>16, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>4],
            ['workflow_id'=>10, 'sequence_no'=>17, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>5],
            ['workflow_id'=>10, 'sequence_no'=>18, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>6],
            ['workflow_id'=>10, 'sequence_no'=>19, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>7],

            //11
            ['workflow_id'=>11, 'sequence_no'=>1, 'office_reference'=>'Applicant', 'role_id'=>1],
            ['workflow_id'=>11, 'sequence_no'=>2, 'office_reference'=>'Institute', 'role_id'=>2],
            ['workflow_id'=>11, 'sequence_no'=>3, 'office_reference'=>'Institute', 'role_id'=>3],
            ['workflow_id'=>11, 'sequence_no'=>4, 'office_reference'=>'Institute', 'role_id'=>4],
            ['workflow_id'=>11, 'sequence_no'=>5, 'office_reference'=>'දකුණු පළාත් සහකාර පළාත් පාලන දෙපාර්තමේන්තුව - මාතර', 'role_id'=>2],
            ['workflow_id'=>11, 'sequence_no'=>6, 'office_reference'=>'දකුණු පළාත් සහකාර පළාත් පාලන දෙපාර්තමේන්තුව - මාතර', 'role_id'=>3],
            ['workflow_id'=>11, 'sequence_no'=>7, 'office_reference'=>'දකුණු පළාත් සහකාර පළාත් පාලන දෙපාර්තමේන්තුව - මාතර', 'role_id'=>4],
            ['workflow_id'=>11, 'sequence_no'=>8, 'office_reference'=>'දකුණු පළාත් පළාත් පාලන දෙපාර්තමේන්තුව', 'role_id'=>2],
            ['workflow_id'=>11, 'sequence_no'=>9, 'office_reference'=>'දකුණු පළාත් පළාත් පාලන දෙපාර්තමේන්තුව', 'role_id'=>3],
            ['workflow_id'=>11, 'sequence_no'=>10, 'office_reference'=>'දකුණු පළාත් පළාත් පාලන දෙපාර්තමේන්තුව', 'role_id'=>4],
            ['workflow_id'=>11, 'sequence_no'=>11, 'office_reference'=>'දකුණු පළාත් ප්‍රධාන අමාත්‍යංශය', 'role_id'=>2],
            ['workflow_id'=>11, 'sequence_no'=>12, 'office_reference'=>'දකුණු පළාත් ප්‍රධාන අමාත්‍යංශය', 'role_id'=>3],
            ['workflow_id'=>11, 'sequence_no'=>13, 'office_reference'=>'දකුණු පළාත් ප්‍රධාන අමාත්‍යංශය', 'role_id'=>4],
            ['workflow_id'=>11, 'sequence_no'=>14, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>2],
            ['workflow_id'=>11, 'sequence_no'=>15, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>3],
            ['workflow_id'=>11, 'sequence_no'=>16, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>4],
            ['workflow_id'=>11, 'sequence_no'=>17, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>5],
            ['workflow_id'=>11, 'sequence_no'=>18, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>6],
            ['workflow_id'=>12, 'sequence_no'=>19, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>7],

            //12
            ['workflow_id'=>12, 'sequence_no'=>1, 'office_reference'=>'Applicant', 'role_id'=>1],
            ['workflow_id'=>12, 'sequence_no'=>2, 'office_reference'=>'Institute', 'role_id'=>2],
            ['workflow_id'=>12, 'sequence_no'=>3, 'office_reference'=>'Institute', 'role_id'=>3],
            ['workflow_id'=>12, 'sequence_no'=>4, 'office_reference'=>'Institute', 'role_id'=>4],
            ['workflow_id'=>12, 'sequence_no'=>5, 'office_reference'=>'දකුණු පළාත් සහකාර පළාත් පාලන දෙපාර්තමේන්තුව - හම්බන්තොට', 'role_id'=>2],
            ['workflow_id'=>12, 'sequence_no'=>6, 'office_reference'=>'දකුණු පළාත් සහකාර පළාත් පාලන දෙපාර්තමේන්තුව - හම්බන්තොට', 'role_id'=>3],
            ['workflow_id'=>12, 'sequence_no'=>7, 'office_reference'=>'දකුණු පළාත් සහකාර පළාත් පාලන දෙපාර්තමේන්තුව - හම්බන්තොට', 'role_id'=>4],
            ['workflow_id'=>12, 'sequence_no'=>8, 'office_reference'=>'දකුණු පළාත් පළාත් පාලන දෙපාර්තමේන්තුව', 'role_id'=>2],
            ['workflow_id'=>12, 'sequence_no'=>9, 'office_reference'=>'දකුණු පළාත් පළාත් පාලන දෙපාර්තමේන්තුව', 'role_id'=>3],
            ['workflow_id'=>12, 'sequence_no'=>10, 'office_reference'=>'දකුණු පළාත් පළාත් පාලන දෙපාර්තමේන්තුව', 'role_id'=>4],
            ['workflow_id'=>12, 'sequence_no'=>11, 'office_reference'=>'දකුණු පළාත් ප්‍රධාන අමාත්‍යංශය', 'role_id'=>2],
            ['workflow_id'=>12, 'sequence_no'=>12, 'office_reference'=>'දකුණු පළාත් ප්‍රධාන අමාත්‍යංශය', 'role_id'=>3],
            ['workflow_id'=>12, 'sequence_no'=>13, 'office_reference'=>'දකුණු පළාත් ප්‍රධාන අමාත්‍යංශය', 'role_id'=>4],
            ['workflow_id'=>12, 'sequence_no'=>14, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>2],
            ['workflow_id'=>12, 'sequence_no'=>15, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>3],
            ['workflow_id'=>12, 'sequence_no'=>16, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>4],
            ['workflow_id'=>12, 'sequence_no'=>17, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>5],
            ['workflow_id'=>12, 'sequence_no'=>18, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>6],
            ['workflow_id'=>13, 'sequence_no'=>19, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>7],

            //13
            ['workflow_id'=>13, 'sequence_no'=>1, 'office_reference'=>'Applicant', 'role_id'=>1],
            ['workflow_id'=>13, 'sequence_no'=>2, 'office_reference'=>'Institute', 'role_id'=>2],
            ['workflow_id'=>13, 'sequence_no'=>3, 'office_reference'=>'Institute', 'role_id'=>3],
            ['workflow_id'=>13, 'sequence_no'=>4, 'office_reference'=>'Institute', 'role_id'=>4],
            ['workflow_id'=>13, 'sequence_no'=>5, 'office_reference'=>'දිස්ත්‍රික් සෞඛ්‍ය සේවා අධ්‍යක්ෂ කාර්යාලය - ගාල්ල', 'role_id'=>2],
            ['workflow_id'=>13, 'sequence_no'=>6, 'office_reference'=>'දිස්ත්‍රික් සෞඛ්‍ය සේවා අධ්‍යක්ෂ කාර්යාලය - ගාල්ල', 'role_id'=>3],
            ['workflow_id'=>13, 'sequence_no'=>7, 'office_reference'=>'දිස්ත්‍රික් සෞඛ්‍ය සේවා අධ්‍යක්ෂ කාර්යාලය - ගාල්ල', 'role_id'=>4],
            ['workflow_id'=>13, 'sequence_no'=>8, 'office_reference'=>'දකුණු පළාත් සෞඛ්‍ය සේවා දෙපාර්තමේන්තුව', 'role_id'=>2],
            ['workflow_id'=>13, 'sequence_no'=>9, 'office_reference'=>'දකුණු පළාත් සෞඛ්‍ය සේවා දෙපාර්තමේන්තුව', 'role_id'=>3],
            ['workflow_id'=>13, 'sequence_no'=>10, 'office_reference'=>'දකුණු පළාත් සෞඛ්‍ය සේවා දෙපාර්තමේන්තුව', 'role_id'=>4],
            ['workflow_id'=>13, 'sequence_no'=>11, 'office_reference'=>'දකුණු පළාත් ප්‍රධාන අමාත්‍යංශය', 'role_id'=>2],
            ['workflow_id'=>13, 'sequence_no'=>12, 'office_reference'=>'දකුණු පළාත් ප්‍රධාන අමාත්‍යංශය', 'role_id'=>3],
            ['workflow_id'=>13, 'sequence_no'=>13, 'office_reference'=>'දකුණු පළාත් ප්‍රධාන අමාත්‍යංශය', 'role_id'=>4],
            ['workflow_id'=>13, 'sequence_no'=>14, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>2],
            ['workflow_id'=>13, 'sequence_no'=>15, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>3],
            ['workflow_id'=>13, 'sequence_no'=>16, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>4],
            ['workflow_id'=>13, 'sequence_no'=>17, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>5],
            ['workflow_id'=>13, 'sequence_no'=>18, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>6],
            ['workflow_id'=>14, 'sequence_no'=>19, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>7],

            //14
            ['workflow_id'=>14, 'sequence_no'=>1, 'office_reference'=>'Applicant', 'role_id'=>1],
            ['workflow_id'=>14, 'sequence_no'=>2, 'office_reference'=>'Institute', 'role_id'=>2],
            ['workflow_id'=>14, 'sequence_no'=>3, 'office_reference'=>'Institute', 'role_id'=>3],
            ['workflow_id'=>14, 'sequence_no'=>4, 'office_reference'=>'Institute', 'role_id'=>4],
            ['workflow_id'=>14, 'sequence_no'=>5, 'office_reference'=>'දිස්ත්‍රික් සෞඛ්‍ය සේවා අධ්‍යක්ෂ කාර්යාලය - මාතර', 'role_id'=>2],
            ['workflow_id'=>14, 'sequence_no'=>6, 'office_reference'=>'දිස්ත්‍රික් සෞඛ්‍ය සේවා අධ්‍යක්ෂ කාර්යාලය - මාතර', 'role_id'=>3],
            ['workflow_id'=>14, 'sequence_no'=>7, 'office_reference'=>'දිස්ත්‍රික් සෞඛ්‍ය සේවා අධ්‍යක්ෂ කාර්යාලය - මාතර', 'role_id'=>4],
            ['workflow_id'=>14, 'sequence_no'=>8, 'office_reference'=>'දකුණු පළාත් සෞඛ්‍ය සේවා දෙපාර්තමේන්තුව', 'role_id'=>2],
            ['workflow_id'=>14, 'sequence_no'=>9, 'office_reference'=>'දකුණු පළාත් සෞඛ්‍ය සේවා දෙපාර්තමේන්තුව', 'role_id'=>3],
            ['workflow_id'=>14, 'sequence_no'=>10, 'office_reference'=>'දකුණු පළාත් සෞඛ්‍ය සේවා දෙපාර්තමේන්තුව', 'role_id'=>4],
            ['workflow_id'=>14, 'sequence_no'=>11, 'office_reference'=>'දකුණු පළාත් ප්‍රධාන අමාත්‍යංශය', 'role_id'=>2],
            ['workflow_id'=>14, 'sequence_no'=>12, 'office_reference'=>'දකුණු පළාත් ප්‍රධාන අමාත්‍යංශය', 'role_id'=>3],
            ['workflow_id'=>14, 'sequence_no'=>13, 'office_reference'=>'දකුණු පළාත් ප්‍රධාන අමාත්‍යංශය', 'role_id'=>4],
            ['workflow_id'=>14, 'sequence_no'=>14, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>2],
            ['workflow_id'=>14, 'sequence_no'=>15, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>3],
            ['workflow_id'=>14, 'sequence_no'=>16, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>4],
            ['workflow_id'=>14, 'sequence_no'=>17, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>5],
            ['workflow_id'=>14, 'sequence_no'=>18, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>6],
            ['workflow_id'=>15, 'sequence_no'=>19, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>7],

            //15
            ['workflow_id'=>15, 'sequence_no'=>1, 'office_reference'=>'Applicant', 'role_id'=>1],
            ['workflow_id'=>15, 'sequence_no'=>2, 'office_reference'=>'Institute', 'role_id'=>2],
            ['workflow_id'=>15, 'sequence_no'=>3, 'office_reference'=>'Institute', 'role_id'=>3],
            ['workflow_id'=>15, 'sequence_no'=>4, 'office_reference'=>'Institute', 'role_id'=>4],
            ['workflow_id'=>15, 'sequence_no'=>5, 'office_reference'=>'දිස්ත්‍රික් සෞඛ්‍ය සේවා අධ්‍යක්ෂ කාර්යාලය - හම්බන්තොට‍', 'role_id'=>2],
            ['workflow_id'=>15, 'sequence_no'=>6, 'office_reference'=>'දිස්ත්‍රික් සෞඛ්‍ය සේවා අධ්‍යක්ෂ කාර්යාලය - හම්බන්තොට‍', 'role_id'=>3],
            ['workflow_id'=>15, 'sequence_no'=>7, 'office_reference'=>'දිස්ත්‍රික් සෞඛ්‍ය සේවා අධ්‍යක්ෂ කාර්යාලය - හම්බන්තොට‍', 'role_id'=>4],
            ['workflow_id'=>15, 'sequence_no'=>8, 'office_reference'=>'දකුණු පළාත් සෞඛ්‍ය සේවා දෙපාර්තමේන්තුව', 'role_id'=>2],
            ['workflow_id'=>15, 'sequence_no'=>9, 'office_reference'=>'දකුණු පළාත් සෞඛ්‍ය සේවා දෙපාර්තමේන්තුව', 'role_id'=>3],
            ['workflow_id'=>15, 'sequence_no'=>10, 'office_reference'=>'දකුණු පළාත් සෞඛ්‍ය සේවා දෙපාර්තමේන්තුව', 'role_id'=>4],
            ['workflow_id'=>15, 'sequence_no'=>11, 'office_reference'=>'දකුණු පළාත් ප්‍රධාන අමාත්‍යංශය', 'role_id'=>2],
            ['workflow_id'=>15, 'sequence_no'=>12, 'office_reference'=>'දකුණු පළාත් ප්‍රධාන අමාත්‍යංශය', 'role_id'=>3],
            ['workflow_id'=>15, 'sequence_no'=>13, 'office_reference'=>'දකුණු පළාත් ප්‍රධාන අමාත්‍යංශය', 'role_id'=>4],
            ['workflow_id'=>15, 'sequence_no'=>14, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>2],
            ['workflow_id'=>15, 'sequence_no'=>15, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>3],
            ['workflow_id'=>15, 'sequence_no'=>16, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>4],
            ['workflow_id'=>15, 'sequence_no'=>17, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>5],
            ['workflow_id'=>15, 'sequence_no'=>18, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>6],
            ['workflow_id'=>16, 'sequence_no'=>19, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>7],

            //16
            ['workflow_id'=>16, 'sequence_no'=>1, 'office_reference'=>'Applicant', 'role_id'=>1],
            ['workflow_id'=>16, 'sequence_no'=>2, 'office_reference'=>'Institute', 'role_id'=>2],
            ['workflow_id'=>16, 'sequence_no'=>3, 'office_reference'=>'Institute', 'role_id'=>3],
            ['workflow_id'=>16, 'sequence_no'=>4, 'office_reference'=>'Institute', 'role_id'=>4],
            ['workflow_id'=>16, 'sequence_no'=>5, 'office_reference'=>'පාලන අංශය', 'role_id'=>2],
            ['workflow_id'=>16, 'sequence_no'=>6, 'office_reference'=>'පාලන අංශය', 'role_id'=>3],
            ['workflow_id'=>16, 'sequence_no'=>7, 'office_reference'=>'පාලන අංශය', 'role_id'=>4],
            ['workflow_id'=>16, 'sequence_no'=>8, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>2],
            ['workflow_id'=>16, 'sequence_no'=>9, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>3],
            ['workflow_id'=>16, 'sequence_no'=>10, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>4],
            ['workflow_id'=>16, 'sequence_no'=>11, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>5],
            ['workflow_id'=>16, 'sequence_no'=>12, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>6],
            ['workflow_id'=>17, 'sequence_no'=>13, 'office_reference'=>'පිරිස් හා පුහුණු අංශය', 'role_id'=>7],
        ]);
    }
}
